#!/usr/bin/env python3
"""
Generate CMake source lists from the original Visual Studio projects.

WHY NOT file(GLOB): the original projects do not compile everything on disk. Sixteen
files are orphans -- dead legacy that no .vcxproj references (tools/find_orphans.py
finds them) -- and a glob would drag them into the build, where they fail for reasons
nobody needs to care about. The .vcxproj <ClCompile> entries are the authoritative
answer to "what is this product made of", so they are what the build should read.

Emits one .cmake per tree into cmake/sources/, each defining a variable:

    WARZ_ETERNITY_SOURCES        src/Eternity        (static lib, built twice)
    WARZ_GAMEENGINE_SOURCES      src/GameEngine      (static lib, built twice)
    WARZ_ECLIPSESTUDIO_SOURCES   src/EclipseStudio   (the client exe)
    WARZ_<SERVER>_SOURCES        server/src/<name>   (own sources only)
    WARZ_<SERVER>_SHARED_SOURCES sources outside server/ that the server compiles

GameEngine has no project file of its own: its sources are listed directly in
Studio.vcxproj (89 entries) and WO_GameServer.vcxproj (47). This script recovers the
GameEngine set from those consumers, which is what lets the port build it once as a
library per configuration instead of recompiling it into every binary.

Usage:
    ./tools/gen_sources.py          # write cmake/sources/*.cmake
    ./tools/gen_sources.py --check  # verify the checked-in lists are current (CI)
"""

import os
import re
import sys

MODERN = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ORIGINAL = os.path.dirname(MODERN)
OUTDIR = os.path.join(MODERN, "cmake", "sources")

PROJECTS = {
    "Eternity":         "src/Eternity/Eternity.vcxproj",
    "Studio":           "src/EclipseStudio/Studio.vcxproj",
    "WO_GameServer":    "server/src/WO_GameServer/WO_GameServer.vcxproj",
    "MasterServer":     "server/src/MasterServer/MasterServer.vcxproj",
    "SupervisorServer": "server/src/SupervisorServer/SupervisorServer.vcxproj",
}

# Kynapse wrapper implementations, superseded by ai/RecastNav/. Their headers survive as
# forwarding shims so call sites compile; the .cpp files have no counterpart. Keep this
# consistent with the same exclusion in probe.sh and find_shared_server_sources.py.
EXCLUDE = re.compile(r"AutodeskNav/Autodesk.*\.cpp$", re.I)


_case_index = {}


def _resolve_case(rel):
    """Map a .vcxproj path onto the real one, ignoring case.

    The projects were authored on Windows, where the filesystem is case-insensitive, so
    they spell paths inconsistently: Studio.vcxproj says ObjectsCode/World/Building.cpp
    and ObjectsCode/Effects/obj_ParticleSystem.cpp while the directories on disk are
    WORLD and EFFECTS, and it says Lake.CPP where the file is Lake.cpp. On Linux those
    are four different files that do not exist, which silently drops live sources from
    the build. Resolve against what is actually there.
    """
    if os.path.isfile(os.path.join(MODERN, rel)):
        return rel

    if not _case_index:
        for root, _dirs, files in os.walk(MODERN):
            for f in files:
                p = os.path.relpath(os.path.join(root, f), MODERN).replace(os.sep, "/")
                _case_index[p.lower()] = p

    return _case_index.get(rel.lower(), rel)


def cl_compile_entries(proj_rel):
    """Every <ClCompile Include="..."> in a project, as paths relative to modern/."""
    path = os.path.join(ORIGINAL, proj_rel)
    with open(path, encoding="utf-8", errors="surrogateescape") as fh:
        text = fh.read()

    base = os.path.dirname(proj_rel)
    out = []
    for m in re.finditer(r'<ClCompile\s+Include="([^"]+)"', text):
        rel = m.group(1).replace("\\", "/")
        full = os.path.normpath(os.path.join(base, rel)).replace(os.sep, "/")
        if EXCLUDE.search(full):
            continue
        out.append(_resolve_case(full))
    return sorted(set(out))


def under(paths, prefix):
    return [p for p in paths if p.startswith(prefix)]


def write_list(name, var, sources, note):
    present = [s for s in sources if os.path.isfile(os.path.join(MODERN, s))]
    missing = [s for s in sources if not os.path.isfile(os.path.join(MODERN, s))]

    lines = [
        "# GENERATED by tools/gen_sources.py -- do not edit by hand.",
        "#",
    ]
    lines += ["# " + l for l in note.strip().splitlines()]
    lines.append("#")
    if missing:
        lines.append("# Referenced by the .vcxproj but not present in modern/ "
                     "(bootstrap.sh does not copy everything):")
        lines += ["#   " + m for m in missing]
        lines.append("#")
    # Anchored to ${WARZ_ROOT}, not relative: CMake resolves a relative source path
    # against CMAKE_CURRENT_SOURCE_DIR, so an unanchored "src/Eternity/..." read from
    # src/Eternity/CMakeLists.txt would be looked for at src/Eternity/src/Eternity/...
    lines.append(f"set({var}")
    lines += [f"    ${{WARZ_ROOT}}/{s}" for s in present]
    lines.append(")")
    text = "\n".join(lines) + "\n"

    dest = os.path.join(OUTDIR, name)
    old = None
    if os.path.isfile(dest):
        with open(dest) as fh:
            old = fh.read()

    return dest, text, old, len(present), len(missing)


def main():
    check = "--check" in sys.argv
    os.makedirs(OUTDIR, exist_ok=True)

    proj = {k: cl_compile_entries(v) for k, v in PROJECTS.items()}

    # GameEngine has no project of its own -- recover it from its two consumers.
    #
    # Unlike every other tree, the .vcxproj entries are NOT the whole answer here, so
    # this is the one place the on-disk set is unioned in as well. Ten live sources are
    # in no project file:
    #   - RmlUiIntegration/ and ai/RecastNav/ (3) were ADDED BY THIS PORT, replacing
    #     Scaleform and Kynapse. No 2013 project could list them.
    #   - TrueNature/CloudPlane/ (6) is reached through SkyDome.h, which every consumer
    #     compiles, and the six files reference each other.
    #   - gameobjects/EventTransport.cpp is included by GameObj.cpp and
    #     ClientGameLogic.cpp.
    # Verified by symbol diff: removing any of them leaves undefined references in the
    # rest of the object set.
    #
    # Taking the on-disk set is safe here in a way it would not be for EclipseStudio:
    # GameEngine is 44 files, has no orphan history, and all 44 compile clean in both
    # configurations. Do not copy this shortcut to the other trees.
    gameengine_disk = []
    ge_root = os.path.join(MODERN, "src/GameEngine")
    for root, _dirs, files in os.walk(ge_root):
        for f in files:
            if not f.endswith((".cpp", ".CPP")):
                continue
            p = os.path.relpath(os.path.join(root, f), MODERN).replace(os.sep, "/")
            if EXCLUDE.search(p):
                continue
            gameengine_disk.append(p)

    ge_client_proj = set(under(proj["Studio"], "src/GameEngine/"))
    ge_server_proj = set(under(proj["WO_GameServer"], "src/GameEngine/"))

    # Where the ten disk-only files belong, decided by what each replaces or is reached
    # from rather than by guesswork:
    #   ai/RecastNav/      <- replaces AutodeskNav, which BOTH projects compile
    #   gameobjects/EventTransport.cpp  <- included by GameObj.cpp, in both
    #   RmlUiIntegration/  <- replaces APIScaleformGfx.cpp, client-only
    #   TrueNature/CloudPlane/  <- reached through SkyDome.h, client-only
    BOTH = ("src/GameEngine/ai/RecastNav/", "src/GameEngine/gameobjects/EventTransport.")
    for p in gameengine_disk:
        if p in ge_client_proj or p in ge_server_proj:
            continue
        ge_client_proj.add(p)
        if p.startswith(BOTH):
            ge_server_proj.add(p)

    ge_common = sorted(ge_client_proj & ge_server_proj)
    ge_client_only = sorted(ge_client_proj - ge_server_proj)
    ge_server_only = sorted(ge_server_proj - ge_client_proj)
    if ge_server_only:
        print("  NOTE: GameEngine sources the server compiles and the client does not:")
        for p in ge_server_only:
            print("        " + p)

    outputs = []
    outputs.append(write_list(
        "Eternity.cmake", "WARZ_ETERNITY_SOURCES",
        under(proj["Eternity"], "src/Eternity/"),
        "src/Eternity/Eternity.vcxproj. Includes SF/ and UndoHistory/, which sit\n"
        "outside Source/ and were missed when the probe was pointed at Source/ alone."))

    ge_note = (
        "GameEngine has no .vcxproj of its own -- the original compiled these sources\n"
        "directly into each consumer (89 entries in Studio.vcxproj, 47 in\n"
        "WO_GameServer.vcxproj). Building them once per configuration as a library is a\n"
        "change this port makes deliberately.\n"
        "\n"
        "Ten live sources appear in no project file at all and are recovered from disk:\n"
        "RmlUiIntegration/ and ai/RecastNav/ were added by this port to replace\n"
        "Scaleform and Kynapse, and TrueNature/CloudPlane/ plus EventTransport.cpp are\n"
        "reached through headers their consumers compile. Each is assigned to the same\n"
        "side as the thing it replaces or is reached from -- see gen_sources.py.")

    outputs.append(write_list(
        "GameEngine.cmake", "WARZ_GAMEENGINE_SOURCES", ge_common,
        ge_note + "\n\nThis list is what BOTH the client and the server compile."))

    outputs.append(write_list(
        "GameEngine_client_only.cmake", "WARZ_GAMEENGINE_CLIENT_ONLY_SOURCES",
        ge_client_only,
        "GameEngine sources only the CLIENT compiles, on top of\n"
        "WARZ_GAMEENGINE_SOURCES. obj_Vehicle.cpp and VehicleManager.cpp are here\n"
        "because they include the client weapon headers, which #error out under\n"
        "WO_SERVER; the rendering-side files (SkyDome's CloudPlane cluster, the RmlUi\n"
        "integration) are here because the server draws nothing."))

    outputs.append(write_list(
        "EclipseStudio.cmake", "WARZ_ECLIPSESTUDIO_SOURCES",
        under(proj["Studio"], "src/EclipseStudio/"),
        "src/EclipseStudio/Studio.vcxproj, EclipseStudio entries only. The GameEngine\n"
        "and External entries in that project are handled by their own targets."))

    for srv in ("WO_GameServer", "MasterServer", "SupervisorServer"):
        entries = proj[srv]
        outputs.append(write_list(
            f"{srv}.cmake", f"WARZ_{srv.upper()}_SOURCES",
            under(entries, "server/"),
            f"server/src/{srv}/{srv}.vcxproj, sources under server/ only."))

        # Sources outside server/ that this binary compiles ITSELF, with WO_SERVER set.
        # These are compiled a second time here -- they are already in the client build
        # under different #ifdef branches -- so they cannot come from a shared library.
        shared = [e for e in entries
                  if not e.startswith("server/")
                  and not e.startswith("src/GameEngine/")
                  and not e.startswith("src/Eternity/")]
        outputs.append(write_list(
            f"{srv}_shared.cmake", f"WARZ_{srv.upper()}_SHARED_SOURCES", shared,
            f"Sources OUTSIDE server/ that {srv}.vcxproj compiles itself, with\n"
            "WO_SERVER defined. Mostly EclipseStudio files reused server-side; they take\n"
            "different #ifdef branches than the client build, so they are compiled again\n"
            "here rather than linked from the client's objects."))

    stale = []
    for dest, text, old, n_present, n_missing in outputs:
        rel = os.path.relpath(dest, MODERN)
        if old != text:
            stale.append(rel)
            if not check:
                with open(dest, "w") as fh:
                    fh.write(text)
        flag = "" if old == text else ("  [STALE]" if check else "  [written]")
        miss = f", {n_missing} absent" if n_missing else ""
        print(f"  {rel:<44} {n_present:>3} sources{miss}{flag}")

    if check and stale:
        print("\nSource lists are out of date. Run ./tools/gen_sources.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
