# GENERATED by tools/gen_sources.py -- do not edit by hand.
#
# GameEngine sources only the CLIENT compiles, on top of
# WARZ_GAMEENGINE_SOURCES. obj_Vehicle.cpp and VehicleManager.cpp are here
# because they include the client weapon headers, which #error out under
# WO_SERVER; the rendering-side files (SkyDome's CloudPlane cluster, the RmlUi
# integration) are here because the server draws nothing.
#
set(WARZ_GAMEENGINE_CLIENT_ONLY_SOURCES
    ${WARZ_ROOT}/src/GameEngine/APIScaleformGfx.cpp
    ${WARZ_ROOT}/src/GameEngine/CSVLog.cpp
    ${WARZ_ROOT}/src/GameEngine/CamouflageDataManager.cpp
    ${WARZ_ROOT}/src/GameEngine/RmlUiIntegration/RmlUiMovie.cpp
    ${WARZ_ROOT}/src/GameEngine/TrueNature/CloudPlane/Cloud.cpp
    ${WARZ_ROOT}/src/GameEngine/TrueNature/CloudPlane/CloudGrid.cpp
    ${WARZ_ROOT}/src/GameEngine/TrueNature/CloudPlane/CloudPlane.cpp
    ${WARZ_ROOT}/src/GameEngine/TrueNature/CloudPlane/SceneParameter.cpp
    ${WARZ_ROOT}/src/GameEngine/TrueNature/CloudPlane/Shader.cpp
    ${WARZ_ROOT}/src/GameEngine/TrueNature/CloudPlane/Shaders.cpp
    ${WARZ_ROOT}/src/GameEngine/TrueNature/HoffmanScatter.cpp
    ${WARZ_ROOT}/src/GameEngine/TrueNature/SkyDome.cpp
    ${WARZ_ROOT}/src/GameEngine/TrueNature/Sun.cpp
    ${WARZ_ROOT}/src/GameEngine/TrueNature/Terrain_Erosion.cpp
    ${WARZ_ROOT}/src/GameEngine/fmod/SoundSys.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/ApexActor.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/ApexFileStream.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/ApexRenderer.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/ApexWorld.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/GenericQuadTree.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/VehicleManager.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/obj_Apex.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/obj_Dummy.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/obj_Sprite.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/obj_Vehicle.cpp
)
