# GENERATED by tools/gen_sources.py -- do not edit by hand.
#
# GameEngine has no .vcxproj of its own -- the original compiled these sources
# directly into each consumer (89 entries in Studio.vcxproj, 47 in
# WO_GameServer.vcxproj). Building them once per configuration as a library is a
# change this port makes deliberately.
# 
# Ten live sources appear in no project file at all and are recovered from disk:
# RmlUiIntegration/ and ai/RecastNav/ were added by this port to replace
# Scaleform and Kynapse, and TrueNature/CloudPlane/ plus EventTransport.cpp are
# reached through headers their consumers compile. Each is assigned to the same
# side as the thing it replaces or is reached from -- see gen_sources.py.
# 
# This list is what BOTH the client and the server compile.
#
set(WARZ_GAMEENGINE_SOURCES
    ${WARZ_ROOT}/src/GameEngine/DebugHelpers.cpp
    ${WARZ_ROOT}/src/GameEngine/TrueNature/ITerrain.cpp
    ${WARZ_ROOT}/src/GameEngine/TrueNature2/Terrain3.cpp
    ${WARZ_ROOT}/src/GameEngine/ai/AI_Brain.cpp
    ${WARZ_ROOT}/src/GameEngine/ai/AI_Tactics.cpp
    ${WARZ_ROOT}/src/GameEngine/ai/NavGenerationHelpers.cpp
    ${WARZ_ROOT}/src/GameEngine/ai/NavRegionManager.cpp
    ${WARZ_ROOT}/src/GameEngine/ai/RecastNav/RecastNavAgent.cpp
    ${WARZ_ROOT}/src/GameEngine/ai/RecastNav/RecastNavMesh.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/AObject.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/EventTransport.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/GameObj.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/ObjManag.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/PhysObj.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/PhysXRepXHelpers.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/PhysXWorld.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/VehicleDescriptor.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/obj_Mesh.cpp
    ${WARZ_ROOT}/src/GameEngine/gameobjects/sceneBox.cpp
)
