# GENERATED by tools/gen_sources.py -- do not edit by hand.
#
# Sources OUTSIDE server/ that MasterServer.vcxproj compiles itself, with
# WO_SERVER defined. Mostly EclipseStudio files reused server-side; they take
# different #ifdef branches than the client build, so they are compiled again
# here rather than linked from the client's objects.
#
set(WARZ_MASTERSERVER_SHARED_SOURCES
    ${WARZ_ROOT}/src/EclipseStudio/Sources/Backend/WOBackendAPI.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/WEAPONS/BaseItemConfig.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/WEAPONS/WeaponConfig.cpp
)
