# GENERATED by tools/gen_sources.py -- do not edit by hand.
#
# server/src/MasterServer/MasterServer.vcxproj, sources under server/ only.
#
set(WARZ_MASTERSERVER_SOURCES
    ${WARZ_ROOT}/server/src/MasterServer/Sources/MasterAsyncApiMgr.cpp
    ${WARZ_ROOT}/server/src/MasterServer/Sources/MasterGameServer.cpp
    ${WARZ_ROOT}/server/src/MasterServer/Sources/MasterServer.cpp
    ${WARZ_ROOT}/server/src/MasterServer/Sources/MasterServerConfig.cpp
    ${WARZ_ROOT}/server/src/MasterServer/Sources/MasterServerMain.cpp
    ${WARZ_ROOT}/server/src/MasterServer/Sources/MasterUdpMonitor.cpp
    ${WARZ_ROOT}/server/src/MasterServer/Sources/MasterUserServer.cpp
    ${WARZ_ROOT}/server/src/MasterServer/Sources/ServerWeapons/MasterServerWeaponArmory.cpp
    ${WARZ_ROOT}/server/src/MasterServer/Sources/SrvCrashHandler.cpp
    ${WARZ_ROOT}/server/src/MasterServer/Sources/VersionNo.cpp
    ${WARZ_ROOT}/server/src/MasterServer/Sources/stdafx.cpp
)
