# Generated by tools/gen_physx_sources.py -- do not edit.
# Derived from PhysX 4.1's own compiler/cmake/{,windows/}PhysXFoundation.cmake.

set(WARZ_PHYSXFOUNDATION_SOURCES
    ${PHYSX_DIR}/physx-source/foundation/src/PsAllocator.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/PsAssert.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/PsFoundation.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/PsMathUtils.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/PsString.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/PsTempAllocator.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/PsUtilities.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/windows/PsWindowsAtomic.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/windows/PsWindowsCpu.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/windows/PsWindowsFPU.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/windows/PsWindowsMutex.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/windows/PsWindowsPrintString.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/windows/PsWindowsSList.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/windows/PsWindowsSocket.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/windows/PsWindowsSync.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/windows/PsWindowsThread.cpp
    ${PHYSX_DIR}/physx-source/foundation/src/windows/PsWindowsTime.cpp
)

set(WARZ_PHYSXFOUNDATION_INCLUDES
    ${PHYSX_DIR}/physx-include
    ${PHYSX_DIR}/pxshared-include
    ${PHYSX_DIR}/physx-source/foundation/include
    ${PHYSX_DIR}/physx-source/foundation/include/windows
)
