# Generated by tools/gen_physx_sources.py -- do not edit.
# Derived from PhysX 4.1's own compiler/cmake/{,windows/}LowLevelAABB.cmake.

set(WARZ_LOWLEVELAABB_SOURCES
    ${PHYSX_DIR}/physx-source/lowlevelaabb/src/BpAABBManager.cpp
    ${PHYSX_DIR}/physx-source/lowlevelaabb/src/BpBroadPhase.cpp
    ${PHYSX_DIR}/physx-source/lowlevelaabb/src/BpBroadPhaseABP.cpp
    ${PHYSX_DIR}/physx-source/lowlevelaabb/src/BpBroadPhaseMBP.cpp
    ${PHYSX_DIR}/physx-source/lowlevelaabb/src/BpBroadPhaseSap.cpp
    ${PHYSX_DIR}/physx-source/lowlevelaabb/src/BpBroadPhaseSapAux.cpp
    ${PHYSX_DIR}/physx-source/lowlevelaabb/src/BpBroadPhaseShared.cpp
    ${PHYSX_DIR}/physx-source/lowlevelaabb/src/BpMBPTasks.cpp
    ${PHYSX_DIR}/physx-source/lowlevelaabb/src/BpSAPTasks.cpp
)

set(WARZ_LOWLEVELAABB_INCLUDES
    ${PHYSX_DIR}/physx-source/common/src/windows
    ${PHYSX_DIR}/physx-source/LowLevelAABB/windows/include
    ${PHYSX_DIR}/physx-source/GpuBroadPhase/include
    ${PHYSX_DIR}/physx-source/GpuBroadPhase/src
    ${PHYSX_DIR}/physx-include
    ${PHYSX_DIR}/physx-source/common/include
    ${PHYSX_DIR}/physx-source/common/src
    ${PHYSX_DIR}/physx-source/geomutils/include
    ${PHYSX_DIR}/physx-source/geomutils/src
    ${PHYSX_DIR}/physx-source/lowlevel/api/include
    ${PHYSX_DIR}/physx-source/lowlevel/common/include/utils
    ${PHYSX_DIR}/physx-source/lowlevel/common/include/pipeline
    ${PHYSX_DIR}/physx-source/lowlevelaabb/include
    ${PHYSX_DIR}/physx-source/lowlevelaabb/src
)
