# Generated by tools/gen_physx_sources.py -- do not edit.
# Derived from PhysX 4.1's own compiler/cmake/{,windows/}PhysXVehicle.cmake.

set(WARZ_PHYSXVEHICLE_SOURCES
    ${PHYSX_DIR}/physx-source/physxvehicle/src/PxVehicleComponents.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/PxVehicleDrive.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/PxVehicleDrive4W.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/PxVehicleDriveNW.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/PxVehicleDriveTank.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/PxVehicleMetaData.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/PxVehicleNoDrive.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/PxVehicleSDK.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/PxVehicleSerialization.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/PxVehicleSuspWheelTire4.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/PxVehicleTireFriction.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/PxVehicleUpdate.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/PxVehicleWheels.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/VehicleUtilControl.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/VehicleUtilSetup.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/VehicleUtilTelemetry.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/physxmetadata/src/PxVehicleAutoGeneratedMetaDataObjects.cpp
    ${PHYSX_DIR}/physx-source/physxvehicle/src/physxmetadata/src/PxVehicleMetaDataObjects.cpp
)

set(WARZ_PHYSXVEHICLE_INCLUDES
    ${PHYSX_DIR}/physx-include
    ${PHYSX_DIR}/physx-source/common/include
    ${PHYSX_DIR}/physx-source/common/src
    ${PHYSX_DIR}/physx-source/physxvehicle/src
    ${PHYSX_DIR}/physx-source/physxvehicle/src/physxmetadata/include
    ${PHYSX_DIR}/physx-source/physxmetadata/extensions/include
    ${PHYSX_DIR}/physx-source/physxmetadata/core/include
    ${PHYSX_DIR}/physx-source/physxextensions/src/serialization/Xml
    ${PHYSX_DIR}/physx-source/pvdsdk/src
    ${PHYSX_DIR}/physx-source/pvd/include
)
