# Generated by tools/gen_physx_sources.py -- do not edit.
# Derived from PhysX 4.1's own compiler/cmake/{,windows/}PhysXCharacterKinematic.cmake.

set(WARZ_PHYSXCHARACTERKINEMATIC_SOURCES
    ${PHYSX_DIR}/physx-source/physxcharacterkinematic/src/CctBoxController.cpp
    ${PHYSX_DIR}/physx-source/physxcharacterkinematic/src/CctCapsuleController.cpp
    ${PHYSX_DIR}/physx-source/physxcharacterkinematic/src/CctCharacterController.cpp
    ${PHYSX_DIR}/physx-source/physxcharacterkinematic/src/CctCharacterControllerCallbacks.cpp
    ${PHYSX_DIR}/physx-source/physxcharacterkinematic/src/CctCharacterControllerManager.cpp
    ${PHYSX_DIR}/physx-source/physxcharacterkinematic/src/CctController.cpp
    ${PHYSX_DIR}/physx-source/physxcharacterkinematic/src/CctObstacleContext.cpp
    ${PHYSX_DIR}/physx-source/physxcharacterkinematic/src/CctSweptBox.cpp
    ${PHYSX_DIR}/physx-source/physxcharacterkinematic/src/CctSweptCapsule.cpp
    ${PHYSX_DIR}/physx-source/physxcharacterkinematic/src/CctSweptVolume.cpp
)

set(WARZ_PHYSXCHARACTERKINEMATIC_INCLUDES
    ${PHYSX_DIR}/physx-include
    ${PHYSX_DIR}/physx-source/common/include
    ${PHYSX_DIR}/physx-source/common/src
    ${PHYSX_DIR}/physx-source/geomutils/include
    ${PHYSX_DIR}/physx-source/geomutils/src
    ${PHYSX_DIR}/physx-source/geomutils/src/contact
    ${PHYSX_DIR}/physx-source/geomutils/src/common
    ${PHYSX_DIR}/physx-source/geomutils/src/convex
    ${PHYSX_DIR}/physx-source/geomutils/src/distance
    ${PHYSX_DIR}/physx-source/geomutils/src/gjk
    ${PHYSX_DIR}/physx-source/geomutils/src/intersection
    ${PHYSX_DIR}/physx-source/geomutils/src/mesh
    ${PHYSX_DIR}/physx-source/geomutils/src/hf
    ${PHYSX_DIR}/physx-source/geomutils/src/pcm
)
