# Generated by tools/gen_physx_sources.py -- do not edit.
# Derived from PhysX 4.1's own compiler/cmake/{,windows/}FastXml.cmake.

set(WARZ_FASTXML_SOURCES
    ${PHYSX_DIR}/physx-source/fastxml/src/PsFastXml.cpp
)

set(WARZ_FASTXML_INCLUDES
    ${PHYSX_DIR}/physx-source/fastxml/include
)
