# Generated by tools/gen_physx_sources.py -- do not edit.
# Derived from PhysX 4.1's own compiler/cmake/{,windows/}PhysXPvdSDK.cmake.

set(WARZ_PHYSXPVDSDK_SOURCES
    ${PHYSX_DIR}/physx-source/pvd/src/PxProfileEventImpl.cpp
    ${PHYSX_DIR}/physx-source/pvd/src/PxPvd.cpp
    ${PHYSX_DIR}/physx-source/pvd/src/PxPvdDataStream.cpp
    ${PHYSX_DIR}/physx-source/pvd/src/PxPvdDefaultFileTransport.cpp
    ${PHYSX_DIR}/physx-source/pvd/src/PxPvdDefaultSocketTransport.cpp
    ${PHYSX_DIR}/physx-source/pvd/src/PxPvdImpl.cpp
    ${PHYSX_DIR}/physx-source/pvd/src/PxPvdMemClient.cpp
    ${PHYSX_DIR}/physx-source/pvd/src/PxPvdObjectModelMetaData.cpp
    ${PHYSX_DIR}/physx-source/pvd/src/PxPvdObjectRegistrar.cpp
    ${PHYSX_DIR}/physx-source/pvd/src/PxPvdProfileZoneClient.cpp
    ${PHYSX_DIR}/physx-source/pvd/src/PxPvdUserRenderer.cpp
)

set(WARZ_PHYSXPVDSDK_INCLUDES
    ${PHYSX_DIR}/physx-include
    ${PHYSX_DIR}/physx-source/pvd/include
    ${PHYSX_DIR}/physx-source/filebuf/include
)
