# Generated by tools/gen_physx_sources.py -- do not edit.
# Derived from PhysX 4.1's own compiler/cmake/{,windows/}SceneQuery.cmake.

set(WARZ_SCENEQUERY_SOURCES
    ${PHYSX_DIR}/physx-source/scenequery/src/SqAABBPruner.cpp
    ${PHYSX_DIR}/physx-source/scenequery/src/SqAABBTree.cpp
    ${PHYSX_DIR}/physx-source/scenequery/src/SqIncrementalAABBPruner.cpp
    ${PHYSX_DIR}/physx-source/scenequery/src/SqIncrementalAABBPrunerCore.cpp
    ${PHYSX_DIR}/physx-source/scenequery/src/SqIncrementalAABBTree.cpp
    ${PHYSX_DIR}/physx-source/scenequery/src/SqAABBTreeUpdateMap.cpp
    ${PHYSX_DIR}/physx-source/scenequery/src/SqBounds.cpp
    ${PHYSX_DIR}/physx-source/scenequery/src/SqCompoundPruner.cpp
    ${PHYSX_DIR}/physx-source/scenequery/src/SqCompoundPruningPool.cpp
    ${PHYSX_DIR}/physx-source/scenequery/src/SqBucketPruner.cpp
    ${PHYSX_DIR}/physx-source/scenequery/src/SqExtendedBucketPruner.cpp
    ${PHYSX_DIR}/physx-source/scenequery/src/SqMetaData.cpp
    ${PHYSX_DIR}/physx-source/scenequery/src/SqPruningPool.cpp
    ${PHYSX_DIR}/physx-source/scenequery/src/SqPruningStructure.cpp
    ${PHYSX_DIR}/physx-source/scenequery/src/SqSceneQueryManager.cpp
)

set(WARZ_SCENEQUERY_INCLUDES
    ${PHYSX_DIR}/physx-source/common/src/windows
    ${PHYSX_DIR}/physx-include
    ${PHYSX_DIR}/physx-source/common/include
    ${PHYSX_DIR}/physx-source/common/src
    ${PHYSX_DIR}/physx-source/geomutils/include
    ${PHYSX_DIR}/physx-source/geomutils/src
    ${PHYSX_DIR}/physx-source/geomutils/src/contact
    ${PHYSX_DIR}/physx-source/geomutils/src/common
    ${PHYSX_DIR}/physx-source/geomutils/src/convex
    ${PHYSX_DIR}/physx-source/geomutils/src/distance
    ${PHYSX_DIR}/physx-source/geomutils/src/sweep
    ${PHYSX_DIR}/physx-source/geomutils/src/gjk
    ${PHYSX_DIR}/physx-source/geomutils/src/intersection
    ${PHYSX_DIR}/physx-source/geomutils/src/mesh
    ${PHYSX_DIR}/physx-source/geomutils/src/hf
    ${PHYSX_DIR}/physx-source/geomutils/src/pcm
    ${PHYSX_DIR}/physx-source/geomutils/src/ccd
    ${PHYSX_DIR}/physx-source/lowlevel/api/include
    ${PHYSX_DIR}/physx-source/scenequery/include
    ${PHYSX_DIR}/physx-source/simulationcontroller/include
    ${PHYSX_DIR}/physx-source/physx/src
    ${PHYSX_DIR}/physx-source/physx/src/buffering
    ${PHYSX_DIR}/physx-source/pvd/include
)
