# Generated by tools/gen_physx_sources.py -- do not edit.
# Derived from PhysX 4.1's own compiler/cmake/{,windows/}PhysXTask.cmake.

set(WARZ_PHYSXTASK_SOURCES
    ${PHYSX_DIR}/physx-source/task/src/TaskManager.cpp
)

set(WARZ_PHYSXTASK_INCLUDES
    ${PHYSX_DIR}/physx-include
    ${PHYSX_DIR}/physx-source/cudamanager/include
)
