# GENERATED by tools/gen_sources.py -- do not edit by hand.
#
# Sources OUTSIDE server/ that SupervisorServer.vcxproj compiles itself, with
# WO_SERVER defined. Mostly EclipseStudio files reused server-side; they take
# different #ifdef branches than the client build, so they are compiled again
# here rather than linked from the client's objects.
#
set(WARZ_SUPERVISORSERVER_SHARED_SOURCES
)
