# GENERATED by tools/gen_sources.py -- do not edit by hand.
#
# server/src/SupervisorServer/SupervisorServer.vcxproj, sources under server/ only.
#
set(WARZ_SUPERVISORSERVER_SOURCES
    ${WARZ_ROOT}/server/src/MasterServer/Sources/MasterUdpMonitor.cpp
    ${WARZ_ROOT}/server/src/MasterServer/Sources/SrvCrashHandler.cpp
    ${WARZ_ROOT}/server/src/SupervisorServer/Sources/GameWatcher.cpp
    ${WARZ_ROOT}/server/src/SupervisorServer/Sources/LogUploader.cpp
    ${WARZ_ROOT}/server/src/SupervisorServer/Sources/SupervisorConfig.cpp
    ${WARZ_ROOT}/server/src/SupervisorServer/Sources/SupervisorGameServer.cpp
    ${WARZ_ROOT}/server/src/SupervisorServer/Sources/SupervisorServer.cpp
    ${WARZ_ROOT}/server/src/SupervisorServer/Sources/SupervisorServerMain.cpp
    ${WARZ_ROOT}/server/src/SupervisorServer/Sources/VersionNo.cpp
    ${WARZ_ROOT}/server/src/SupervisorServer/Sources/stdafx.cpp
)
