# GENERATED by tools/gen_sources.py -- do not edit by hand.
#
# Sources OUTSIDE server/ that WO_GameServer.vcxproj compiles itself, with
# WO_SERVER defined. Mostly EclipseStudio files reused server-side; they take
# different #ifdef branches than the client build, so they are compiled again
# here rather than linked from the client's objects.
#
set(WARZ_WO_GAMESERVER_SHARED_SOURCES
    ${WARZ_ROOT}/src/EclipseStudio/Sources/Backend/WOBackendAPI.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/DamageLib.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/Editors/CollectionElement.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/Editors/CollectionType.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/Editors/CollectionsManager.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/GameCode/UserProfile.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/GameCode/UserRewards.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/GameLevel.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/GameLevel_IO.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/Gameplay/BaseItemSpawnPoint.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/Gameplay/BasePlayerSpawnPoint.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/Gameplay/BaseVehicleSpawnPoint.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/Gameplay/obj_NoClipBox.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/Nature/obj_Terrain.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/WEAPONS/BaseItemConfig.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/WEAPONS/GearConfig.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/WEAPONS/HeroConfig.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/WEAPONS/WeaponArmory.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/WEAPONS/WeaponConfig.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/WORLD/DecalChief.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/WORLD/Lake.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/WORLD/MaterialTypes.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/WORLD/PrefabManager.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/WORLD/WaterPlane.CPP
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/WORLD/obj_Prefab.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/ObjectsCode/WORLD/water.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/XMLHelpers.cpp
    ${WARZ_ROOT}/src/EclipseStudio/Sources/multiplayer/NetCellMover.cpp
)
